name: Xích Kê
slogan: Bổn gà chất lượng cao
title: Xích Kê | Trại Gà Mỹ Rặc Nhập Khẩu | Chuyên Gà Đá Chiến Kê
description: Xích Kê | Trại Gà Mỹ Rặc Nhập Khẩu | chuyên phân phối gà đá từ Mỹ
url: https://xichke.com/
images:
  - https://xichke.com/photos/xich-ke.jpg
  - https://xichke.com/photos/xich-ke-01.jpg
  - https://xichke.com/photos/xich-ke-02.jpg
  - https://xichke.com/photos/xich-ke-03.jpg
  - https://xichke.com/photos/profile.jpg
fb_app_id: 1782964465289118
fb_admins: 
    - 100009152644081
    - trangsinh
fb_page: https://www.facebook.com/xichkedotcom
youtube_channel: https://www.youtube.com/xichke
phone: 0944200387
address: Biên Hoà Đồng Nai

menu:
  - name: Bổn Bang
    url: /bon-bang
    icon: bx bx-star
  - name: Chăm Sóc
    url: /cham-soc
    icon: bx bx-first-aid
  - name: Sản Phẩm
    url: /san-pham
    icon: bx bxs-cart
  - name: Trang Trại
    url: /trang-trai
    icon: bx bx-trophy
  - name: Liên Hệ
    url: /lien-he
    icon: bx bx-phone-call
  - name: Chia Sẻ
    url: /chia-se
    icon: bx bx-share-alt
assets:
  css:
    - vendors/css/vendors.min.css
    - css/bootstrap.css
    - css/bootstrap-extended.css
    - css/colors.css
    - css/components.css
    - css/themes/dark-layout.css
    - css/themes/semi-dark-layout.css
    - css/core/menu/menu-types/horizontal-menu.css
    - css/site.css
  js:
    - vendors/js/vendors.min.js
    - vendors/js/ui/jquery.sticky.js
    - js/scripts/configs/horizontal-menu.min.js
    - js/core/app-menu.js
    - js/core/app.js
    - js/scripts/components.min.js
    - js/scripts/footer.min.js