page_name: Xích Kê
title: Xích Kê | Trại Gà Mỹ Rặc Nhập Khẩu | Chuyên Gà Đá Chiến Kê
description: Xích Kê | Trại Gà Mỹ Rặc Nhập Khẩu | chuyên phân phối gà đá từ Mỹ
url: https://xichke.com/
images:
  - https://xichke.com/photos/xich-ke.jpg
  - https://xichke.com/photos/xich-ke-01.jpg
  - https://xichke.com/photos/xich-ke-02.jpg
  - https://xichke.com/photos/xich-ke-03.jpg
  - https://xichke.com/photos/profile.jpg
name: Xích Kê
fb_app_id: 1782964465289118
fb_admins: 
    - 100009152644081
    - trangsinh
fb_page: https://www.facebook.com/xichkedotcom/
youtube_channel: https://www.youtube.com/xichke
phone: 0911779917
address: Biên Hoà Đồng Nai